spring.application.name=payment-service

server.port=9094

razorpay.key.id=${razorpay.key.id}
razorpay.key.secret=${razorpay.key.secret}

applog.dir=D:\\Data\\EcommerceWorkspace\\logs\\paymentservice

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/